# Generated by Django 2.0.6 on 2018-06-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
