# Generated by Django 2.0.6 on 2018-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_app', '0002_auto_20180607_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
